---
## Info (for the configuration of the further parameters):
# https://docs.ansible.com/ansible/latest/collections/community/general/jenkins_script_module.html
# https://github.com/meierw/jenkins-config
# https://github.com/karlmdavis/ansible-role-jenkins2
# see also: example_configs.xml


## Configure Jenkins Using Groovy Scripts.

# 01 # Ensure that Jenkins has restarted, if it needs to.
- meta: flush_handlers

# 02 # Configure "System Admin e-mail address" Using Groovy Script.
- name: Set System Admin e-mail address in Jenkins
  community.general.jenkins_script:
    script: |
      import jenkins.model.*
      def jenkinsLocationConfiguration = JenkinsLocationConfiguration.get()
      jenkinsLocationConfiguration.setAdminAddress("{{ admin_email }}")
      jenkinsLocationConfiguration.save()
    user: "None"
    password: "None"
    url: http://localhost:8080
  register: configure_email
  # Not reporting as changed (todo)
  changed_when: configure_email.changed

# 03 # Set Jenkins e-mail notification.
- name: Set Jenkins e-mail notification
  jenkins_script:
    url: "{{ jenkins_config_url }}"
    user: "{{ jenkins_config_user }}"
    password: "{{ jenkins_config_password }}"
    script: "{{ lookup('template', 'templates/setEmailNotification.groovy') }}"
  when:
    - jenkins_config_email_notification.smtp_server is defined
    - jenkins_config_email_notification.smtp_server|length > 0