---
## Info (for the configuration of the further parameters):
# https://docs.ansible.com/ansible/latest/collections/community/general/jenkins_script_module.html
# https://github.com/meierw/jenkins-config
# https://github.com/karlmdavis/ansible-role-jenkins2


## Configure Jenkins Using Groovy Scripts.

# 01 # Ensure that Jenkins has restarted, if it needs to.
- meta: flush_handlers

# 02 # Configure "System Admin e-mail address" Using Groovy Script.
- name: Set System Admin e-mail address in Jenkins
  community.general.jenkins_script:
    script: |
      import jenkins.model.*
      def jenkinsLocationConfiguration = JenkinsLocationConfiguration.get()
      jenkinsLocationConfiguration.setAdminAddress("admin-soka-bau@example.com")
      jenkinsLocationConfiguration.save()
    user: "None"
    password: "None"
    url: http://localhost:8080
  register: configure_email
  changed_when: configure_email.changed