---
# Tasks file for jenkins
- name: Set facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Execute RHEL tasks
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_os_family == "RedHat"