---
# Install and Configure NGINX as a Reverse Proxy

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

- name: Download EPEL release package
  ansible.builtin.get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    dest: /tmp/epel-release-latest-9.noarch.rpm

- name: Install EPEL release package
  ansible.builtin.dnf:
    name: /tmp/epel-release-latest-9.noarch.rpm
    state: present

- name: Install NGINX
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Start and enable NGINX
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

# Import .crt and .key files
- name: Copy files (.crt and .key) starting with the hostname
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/ssl/certs/"
  with_fileglob:
    - "certificates/{{ ansible_hostname }}*"

# Configure Nginx with SSL certificates named after the hostname
- name: Deploy NGINX Reverse Proxy Configuration
  ansible.builtin.template:
    src: configs/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
