---

# install jenkins for RHEL

- name: redhat | Download Long Term Jenkins release
  get_url:
    url: "{{ jenkins_repo }}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true
  register: result
  until: result is successful
  
- name: redhat | Importing the key 
  ansible.builtin.rpm_key:
    state: present
    key: "{{ jenkins_key }}"
  become: true

- name: redhat | update the system
  ansible.builtin.yum:
    name: "*"
    state: latest
  become: true

- name: redhat | install dependencies fontconfig
  ansible.builtin.yum:
    name: fontconfig
    state: present
  become: true

- name: redhat | install java for jenkins 
  ansible.builtin.yum: 
    name: "{{ java_version }}"
    state: present
  become: true

#### TODO: Params ####
- name: redhat | correct java version selected
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-17-openjdk-17.0.10.0.7-2.el9.x86_64/bin/java
    state: present

- name: redhat | Installing jenkins 
  ansible.builtin.yum:
    name: "{{ jenkins_package }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: rhel | daemon-reload to pick up config changes
  ansible.builtin.systemd:
      daemon_reload: yes
  become: true

  # Configure Jenkins init settings.
- include_tasks: settings.yml

- name: rhel | Start jenkins
  ansible.builtin.systemd:
      name: "{{ jenkins_service }}"
      state: started
      enabled: true
  become: true

#- name: rhel | Open Firewall Port
#  ansible.posix.firewalld:
#    port: 8080/tcp
#    permanent: yes
#    state: enabled
#    zone: public
#    immediate: yes
#  become: true
#  when: ansible_facts.services['firewalld.service'].state == 'started'
#  notify: "{{ firewalld_service }}"

# Update Jenkins and install configured plugins.
- include_tasks: plugins.yml
