---
## Configure Jenkins: jenkins proxy, jenkins init file, override default init settings:
## /etc/systemd/system/jenkins.service.d/override.conf.

# 01 #  Check if jenkins_init_folder exists.
- name: Check if jenkins_init_folder exists.
  stat:
    path: "{{ jenkins_init_folder }}"
  register: jenkins_init_folder_stat

# 02 # Ensure jenkins_init_folder exists.
- name: Ensure jenkins_init_folder exists.
  file:
    path: "{{ jenkins_init_folder }}"
    state: directory
    mode: 0644
  when: not jenkins_init_folder_stat.stat.exists

# 03 # Check if jenkins_init_file exists.
- name: Check if jenkins_init_file exists.
  stat:
    path: "{{ jenkins_init_file }}"
  register: jenkins_init_file_stat

# 04 # Ensure jenkins_init_file exists.
- name: Ensure jenkins_init_file exists.
  file:
    path: "{{ jenkins_init_file }}"
    state: touch
    mode: 0644
  when: not jenkins_init_file_stat.stat.exists

# 05 # Populate jenkins_init_file with service tag.
- name: Populate jenkins_init_file with service tag.
  copy:
    dest: "{{ jenkins_init_file }}"
    content: "[Service]"
  when: not jenkins_init_file_stat.stat.exists

# 06 # Modify variables in init file.
- name: Modify variables in init file.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^Environment="{{ item.option }}='
    regexp: '^Environment="{{ item.option }} '
    line: 'Environment="{{ item.option }}={{ item.value }}"'
    state: present
    mode: 0644
  with_items: "{{ jenkins_init_changes }}"
  register: jenkins_init_prefix

# 07 # Ensure jenkins_home {{ jenkins_home }} exists.
- name: Ensure jenkins_home {{ jenkins_home }} exists.
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: u+rwx
    follow: true

# 08 # Immediately restart Jenkins on init config changes.
- name: Immediately restart Jenkins on init config changes.
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: true
  when: jenkins_init_prefix.changed

# 09 # Create custom init scripts directory.
- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

# 10 # Configure proxy config for Jenkins, if Jenkins is behind a proxy.
- name: Configure proxy config for Jenkins
  template:
    src: proxy.xml
    dest: "{{ jenkins_home }}/proxy.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0664
  register: jenkins_proxy_config
  when:
    - jenkins_proxy_host | length > 0
    - jenkins_proxy_port | length > 0

# 11 # Trigger handlers immediately in case Jenkins was installed.
- name: Trigger handlers immediately in case Jenkins was installed
  meta: flush_handlers

# 12 # Immediately restart Jenkins on http or user changes.
- name: Immediately restart Jenkins on http or user changes.
  service: name=jenkins state=restarted
  when: >
    (jenkins_users_config is defined and jenkins_users_config.changed)
    or (jenkins_http_config is defined and jenkins_http_config.changed)
    or (jenkins_home_config is defined and jenkins_home_config.changed)
    or (jenkins_proxy_config is defined and jenkins_proxy_config.changed)