---
# Handlers

# 01 # Restart Jenkins server
- name: restart jenkins
  ansible.builtin.service:
    name: jenkins
    state: restarted
  become: true

# 02 # Restart FirewallD service
- name: restart firewalld
  ansible.builtin.service:
    name: firewalld.service
    state: restarted
  become: true

# 03 # Restart NGINX server
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted